# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        CA\BlogBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: true
            iterations: 5000


    providers:
        users_db:
            entity:
                #class: AppBundle:User
                class: CABlogBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            provider: users_db
            # activate different ways to authenticate
            form_login:
                login_path: login
                check_path: login
                failure_path_parameter: back_to
                username_parameter: _username
                password_parameter: _password
                post_only: true
                require_previous_session: true
                remember_me:    true

            remember_me:
                secret: '%secret%'
                lifetime: 604800 # in seconds
                path: /

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            logout:
                path:   /logout
                target: /
                delete_cookies:
                    a: { path: null, domain: null }
                    b: { path: null, domain: null }
    
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/blogger, roles: ROLE_BLOGGER }

    access_decision_manager:
        strategy: unanimous

    role_hierarchy:
        ROLE_ADMIN:     [ROLE_BLOGGER, ROLE_ADMIN]
        ROLE_BLOGGER:       [ROLE_BLOGGER]
